version: "2"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
          - "db"
    links:
      - "db:mysql"
  db:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=shareit
      - MYSQL_USER=shareit
      - MYSQL_PASSWORD=pass
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    expose:
        - "3306"
    volumes:
          - ./db-dump:/docker-entrypoint-initdb.d
